# Generated by Django 5.0.6 on 2024-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_announcements_alter_club_discussions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='college',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='interest',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='rollno',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='semester',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
