# Generated by Django 5.0.6 on 2024-05-16 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_likeannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeannouncement',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='clubs.announcement'),
        ),
    ]
