# Generated by Django 5.0.6 on 2024-05-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_likeannouncement_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubapplication',
            name='status',
        ),
    ]
